<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="17595" started-at="2019-07-10T05:42:10Z" finished-at="2019-07-10T05:42:27Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="17595" started-at="2019-07-10T05:42:10Z" finished-at="2019-07-10T05:42:27Z">
      <class name="SimpleProject.DemoProject.ReportsLoginLogoutTest">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:SimpleProject.DemoProject.ReportsLoginLogoutTest@649d209a]" name="beforeMethod" is-config="true" duration-ms="3608" started-at="2019-07-10T11:12:10Z" finished-at="2019-07-10T11:12:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login()[pri:0, instance:SimpleProject.DemoProject.ReportsLoginLogoutTest@649d209a]" name="login" duration-ms="11530" started-at="2019-07-10T11:12:13Z" finished-at="2019-07-10T11:12:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Incorrect Username Password]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Incorrect Username Password
	at org.testng.Assert.fail(Assert.java:94)
	at SimpleProject.DemoProject.ReportsLoginLogoutTest.login(ReportsLoginLogoutTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:SimpleProject.DemoProject.ReportsLoginLogoutTest@649d209a]" name="afterMethod" is-config="true" duration-ms="2439" started-at="2019-07-10T11:12:25Z" finished-at="2019-07-10T11:12:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- SimpleProject.DemoProject.ReportsLoginLogoutTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite1 -->
</testng-results>
